adapters: 
  - ws
  - http
debug: false
enableVerify: false
singleMode: false
cacheSize: 4096
persistenceFactory: 'built-in'
adapterSettings:
  http: 
    host: 0.0.0.0
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 100
  ws:
    host: 0.0.0.0
    port: 8080
    reservedSyncId: -1