on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: deploy to server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "Deploying"
        LASTSSH: "Starting deploy docker"
      with:
        host: ${{secrets.DEPLOY_HOST}}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        port: ${{ secrets.DEPLOY_SSH_PORT }}
        connect_timeout: 10s
        first_ssh: |
          rm -rf ~/bot_deploy
        scp: |
          './' => ~/bot_deploy
        last_ssh: |
          cd ~/bot_deploy &&
          cp ~/.env ./ &&
          docker-compose pull --build &&
          docker-compose up -d
